const API_TIMEOUT_MS = 60_000;

const DEFAULT_CONFIG = {
  AI_PROVIDER: "pollinations",
  POLLINATIONS_API_BASE_URL: "https://gen.pollinations.ai",
  POLLINATIONS_API_KEY: "",
  POLLINATIONS_IMAGE_MODEL: "kontext",
  GITHUB_TOKEN: "",
};

const FALLBACK_IMAGE_MODELS = [
  { value: "kontext", label: "kontext (image+edit)", paidOnly: false },
  { value: "flux", label: "flux", paidOnly: false },
  { value: "gptimage", label: "gptimage", paidOnly: false },
];

function getConfig() {
  if (typeof window === "undefined") {
    return { ...DEFAULT_CONFIG };
  }

  return {
    ...DEFAULT_CONFIG,
    ...(window.POSE_EDITOR_CONFIG || {}),
  };
}

function getPrompt() {
  return (
    "You are editing a reference image using an additional 2D pose guide.\n\n" +
    "IMAGE 0 (MAIN REFERENCE):\n" +
    "- This is the original artwork or photo.\n" +
    "- You MUST follow this image for: art style (anime vs realistic, painterly vs flat), line quality, rendering style, color palette, lighting, character identity, age, body type, gender, clothing design and colors, and overall background and camera framing.\n" +
    "- Do not change the number of visible characters or turn them into different characters.\n\n" +
    "IMAGE 1 (POSE GUIDE FROM EDITOR):\n" +
    "- This is the pose guide generated by the pose editor.\n" +
    "- Use this image ONLY to change the body posture of the character(s) from IMAGE 0.\n" +
    "- Treat the guide as the target body alignment in 2D.\n\n" +
    "TASK:\n" +
    "- Produce a new image that looks like a natural redraw of IMAGE 0, in exactly the same style and with the same character(s) and background.\n" +
    "- Adjust the body pose so it clearly matches the pose from IMAGE 1.\n" +
    "- Keep faces, hair, clothing, proportions, camera angle, and background as close as possible to IMAGE 0.\n" +
    "- Do NOT draw or overlay any rigs, joints, sticks, guides, or pose markers in the final result.\n" +
    "- The final image must look like a normal finished illustration or photo that has simply changed pose."
  );
}

function normalizeBaseUrl(url) {
  return url.replace(/\/$/, "");
}

function parseCostNumber(value) {
  if (typeof value === "number") {
    return Number.isFinite(value) ? value : null;
  }
  if (typeof value === "string") {
    const parsed = Number.parseFloat(value);
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
}

function toModelOption(model) {
  const completionImageCost = parseCostNumber(model?.pricing?.completionImageTokens);
  const costLabel = completionImageCost !== null ? `${completionImageCost.toExponential(2)} pollen/img` : "cost: n/a";
  const supportsImageInput = Array.isArray(model?.input_modalities) && model.input_modalities.includes("image");
  const capability = supportsImageInput ? "image+edit" : "image-gen";
  const paidTag = model?.paid_only ? " paid" : "";
  return {
    value: model.name,
    label: `${model.name} (${capability}${paidTag}, ${costLabel})`,
    paidOnly: !!model?.paid_only,
    supportsImageInput,
    supportsImageOutput:
      Array.isArray(model?.output_modalities) && model.output_modalities.includes("image"),
  };
}

export async function fetchImageModels() {
  const config = getConfig();
  const baseUrl = normalizeBaseUrl(config.POLLINATIONS_API_BASE_URL);

  try {
    const response = await fetch(`${baseUrl}/image/models`);
    if (!response.ok) {
      throw new Error(`Image model fetch failed: ${response.status}`);
    }

    const catalog = await response.json();
    if (!Array.isArray(catalog)) {
      throw new Error("Unexpected model response.");
    }

    return catalog
      .filter((model) => model && typeof model.name === "string")
      .map(toModelOption)
      .filter((model) => model.supportsImageOutput)
      .sort((a, b) => a.label.localeCompare(b.label));
  } catch {
    return [...FALLBACK_IMAGE_MODELS];
  }
}

export function filterImageModelsByCapability(models, { requiresImageInput = true, allowPaid = false } = {}) {
  return (models || []).filter((model) => {
    if (!allowPaid && model.paidOnly) return false;
    if (requiresImageInput && !model.supportsImageInput && model.value !== "kontext") return false;
    return true;
  });
}

export function setSelectedImageModel(modelName) {
  if (typeof window === "undefined") return;
  if (!window.POSE_EDITOR_CONFIG) {
    window.POSE_EDITOR_CONFIG = {};
  }
  window.POSE_EDITOR_CONFIG.POLLINATIONS_IMAGE_MODEL = modelName;
}

function getApiKey(config) {
  return config.POLLINATIONS_API_KEY || config.GITHUB_TOKEN || "";
}

async function parseErrorResponse(response) {
  try {
    const data = await response.json();
    return data?.error?.message || data?.message || `${response.status} ${response.statusText}`;
  } catch {
    return `${response.status} ${response.statusText}`;
  }
}

async function postJson(url, options) {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), API_TIMEOUT_MS);

  try {
    const response = await fetch(url, { ...options, signal: controller.signal });
    clearTimeout(timeoutId);

    if (!response.ok) {
      throw new Error(await parseErrorResponse(response));
    }

    return await response.json();
  } catch (err) {
    clearTimeout(timeoutId);
    if (err.name === "AbortError") {
      throw new Error("Request timed out after 60 s. Please try again.");
    }
    throw err;
  }
}

async function generateWithWebsim(imageDataUrl, poseImageDataUrl) {
  if (typeof websim === "undefined" || !websim.imageGen) {
    return null;
  }

  const image_inputs = [];
  if (imageDataUrl) image_inputs.push({ url: imageDataUrl });
  if (poseImageDataUrl) image_inputs.push({ url: poseImageDataUrl });

  const result = await websim.imageGen({
    prompt: getPrompt(),
    image_inputs,
  });

  return result && result.url ? result.url : null;
}

async function generateWithPollinations(imageDataUrl, poseImageDataUrl, config) {
  const key = getApiKey(config);
  if (!key) {
    throw new Error("AI generation is not configured. Set POLLINATIONS_API_KEY (or GITHUB_TOKEN fallback) in config.runtime.js.");
  }

  const payload = {
    model: config.POLLINATIONS_IMAGE_MODEL || "kontext",
    prompt: getPrompt(),
    image: [imageDataUrl, poseImageDataUrl],
    size: "1024x1024",
  };

  const baseUrl = normalizeBaseUrl(config.POLLINATIONS_API_BASE_URL);
  const url = `${baseUrl}/v1/images/edits?key=${encodeURIComponent(key)}`;
  const result = await postJson(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  const imageData = result?.data?.[0];
  if (imageData?.url) {
    return imageData.url;
  }
  if (imageData?.b64_json) {
    return `data:image/png;base64,${imageData.b64_json}`;
  }
  return null;
}

/// Re-draw an uploaded image so the main figure matches the given pose.
export async function generatePoseImage(imageDataUrl, pose, poseImageDataUrl) {
  const config = getConfig();
  const provider = config.AI_PROVIDER || "pollinations";

  try {
    if (provider === "websim") {
      return await generateWithWebsim(imageDataUrl, poseImageDataUrl);
    }

    if (provider === "pollinations") {
      const websimResult = await generateWithWebsim(imageDataUrl, poseImageDataUrl);
      if (websimResult) {
        return websimResult;
      }
      return await generateWithPollinations(imageDataUrl, poseImageDataUrl, config);
    }

    throw new Error(`Unsupported AI provider: ${provider}`);
  } catch (e) {
    console.error(e);
    throw e;
  }
}