/// Use websim image generation to re-draw an uploaded image so the main figure matches the given pose.
export async function generatePoseImage(imageDataUrl, pose, poseImageDataUrl) {
  if (typeof websim === "undefined" || !websim.imageGen) {
    return null;
  }

  try {
    const image_inputs = [];

    // IMAGE 0: original/reference image — style, character, clothing, background
    if (imageDataUrl) {
      image_inputs.push({ url: imageDataUrl });
    }

    // IMAGE 1: pose guide rendered from the editor canvas
    if (poseImageDataUrl) {
      image_inputs.push({ url: poseImageDataUrl });
    }

    const result = await websim.imageGen({
      prompt:
        "You are editing a reference image using an additional 2D pose guide.\n\n" +
        "IMAGE 0 (MAIN REFERENCE):\n" +
        "- This is the original artwork or photo.\n" +
        "- You MUST follow this image for: art style (anime vs realistic, painterly vs flat), line quality, rendering style, color palette, lighting, character identity, age, body type, gender, clothing design and colors, and overall background and camera framing.\n" +
        "- Do not change the number of visible characters or turn them into different characters.\n\n" +
        "IMAGE 1 (POSE GUIDE FROM EDITOR):\n" +
        "- This is a simple orange segment pose reference generated by the pose editor.\n" +
        "- Use this image ONLY to change the body posture of the character(s) from IMAGE 0.\n" +
        "- Treat the orange segments as the spine, arms, and legs of the character in 2D.\n\n" +
        "TASK:\n" +
        "- Produce a new image that looks like a natural redraw of IMAGE 0, in exactly the same style and with the same character(s) and background.\n" +
        "- Adjust the body pose so it clearly matches the pose from IMAGE 1.\n" +
        "- Keep faces, hair, clothing, proportions, camera angle, and background as close as possible to IMAGE 0.\n" +
        "- Do NOT draw or overlay any rigs, joints, sticks, guides, orange segments, or pose markers in the final result.\n" +
        "- The final image must look like a normal finished illustration or photo that has simply changed pose.",
      image_inputs,
    });

    return result && result.url ? result.url : null;
  } catch (e) {
    console.error(e);
    return null;
  }
}